config/routes.rb
Newsman::Application.routes.draw do
  resources :articles

  resources :sections

  resources :issues

  resources :publications

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :articles
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :section_name %><br />
    <%= f.text_field :section_name %>
  </div>
  <div class="field">
    <%= f.label :columns %><br />
    <%= f.number_field :columns %>
  </div>
  <div class="field">
    <%= f.label :gutter %><br />
    <%= f.number_field :gutter %>
  </div>
  <div class="field">
    <%= f.label :grid_height %><br />
    <%= f.number_field :grid_height %>
  </div>
  <div class="field">
    <%= f.label :direction %><br />
    <%= f.check_box :direction %>
  </div>
  <div class="field">
    <%= f.label :design_template %><br />
    <%= f.text_field :design_template %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br />
    <%= f.number_field :issue_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <tr>
    <th>Section name</th>
    <th>Columns</th>
    <th>Gutter</th>
    <th>Grid height</th>
    <th>Direction</th>
    <th>Design template</th>
    <th>Issue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr>
    <td><%= section.section_name %></td>
    <td><%= section.columns %></td>
    <td><%= section.gutter %></td>
    <td><%= section.grid_height %></td>
    <td><%= section.direction %></td>
    <td><%= section.design_template %></td>
    <td><%= section.issue_id %></td>
    <td><%= link_to 'Show', section %></td>
    <td><%= link_to 'Edit', edit_section_path(section) %></td>
    <td><%= link_to 'Destroy', section, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Section name:</b>
  <%= @section.section_name %>
</p>

<p>
  <b>Columns:</b>
  <%= @section.columns %>
</p>

<p>
  <b>Gutter:</b>
  <%= @section.gutter %>
</p>

<p>
  <b>Grid height:</b>
  <%= @section.grid_height %>
</p>

<p>
  <b>Direction:</b>
  <%= @section.direction %>
</p>

<p>
  <b>Design template:</b>
  <%= @section.design_template %>
</p>

<p>
  <b>Issue:</b>
  <%= @section.issue_id %>
</p>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>